language: node_js

node_js:
  - 8.9.4

sudo: true

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - cd Training_node/first_project
  - psql -c "CREATE DATABASE first_project_test;" -U postgres
  - psql -c "CREATE ROLE first_project_test WITH SUPERUSER CREATEDB LOGIN PASSWORD 'first_project_test';" -d first_project_test
  - npm install
  - npm run migrations
